### ISSUE TITLE
PC浏览器拖拽按钮中的图片问题

### ISSUE THREAD

**Issue by xiaokafei666** [ThinkingThigh/vue-draggable-button#5]
在PC浏览器中，拖拽的dom中含有img时，松鼠标，dom未放下；
solution: img标签添加 :draggable="false"；

**Comment by ThinkingThigh** [comment]
Adding :draggable="false" to the img tags is really a good way. I will update the demo on README.md file~ tks！

**Comment by ThinkingThigh** [comment]
Job Done！~
